---
- name: install the required files
  apt:
    name: "{{ item.name }}"
    state: present
  loop: "{{ packages }}"
  when: item.tagged == "baseOS"
- name: create the tftp directory
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop: "{{ directories }}"
- name: copy grubnetx64.efi.signed
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0755'
  loop: "{{ copyfiles }}"
  when: item.priority == 1
