---
- name: include the first task
  include_tasks: install_packages.yml

- name: include the second task
  include_tasks: second_task.yml
- name: include the third task
  include_tasks: third_task.yml
- name: include the workerfs
  include_tasks: workerfs.yml
