---
- name: include the first task
  include_tasks: install_packages.yml

- name: include the second task
  include_tasks: dnsmasq.yml
- name: include the third task
  include_tasks: dhcp_hosts.yml
- name: include the workerfs
  include_tasks: workerfs.yml
- name: include the chroot
  include_tasks: chroot.yml
