---
- name: set up the server
  hosts: localhost
  become: true
  vars_prompt:
    - name: "interface"
      prompt: "Enter the correct interface"
      private: no
    - name: "dhcp_start"
      prompt: "Set the dhcp starting range"
      private: no
    - name: "dhcp_end"
      prompt: "Set the dhcp ending range"
      private: no
    - name: "server_ip"
      prompt: "Set the server ip"
      private: no
    - name: "tftp_root"
      prompt: "Set the tftp root directory "
      private: no
      default: "/srv/tftp"
  tasks:
  - name: Writing the prompt to hosts
    template:
      src: hosts.j2
      dest: "/etc/dnsmasq.d/01-test.hosts"
to be modify
