---
- name: set up the server
  hosts: localhost
  vars_files:
  - requirements.yml
  - dirs.yml
  vars_prompt:
    - name: "interface"
      prompt: "Enter the correct interface"
      private: no
    - name: "dhcp_start"
      prompt: "Set the dhcp starting range"
      private: no
    - name: "dhcp_end"
      prompt: "Set the dhcp ending range"
      private: no
    - name: "server_ip"
      prompt: "Set the server ip"
      private: no
    - name: "tftp_root"
      prompt: "Set the tftp root directory "
      private: no
      default: "/srv/tftp"
  tasks:
  - name: install the required files
    apt:
      name: "{{ item.name }}"
      state: present
    loop: "{{ packages }}"
  - name: create the tftp directory
    file:
      path: "{{ item.path }}"
      state: directory
      mode: "{{ item.mode }}"
    loop: "{{ directories }}"
  - name: Write the input strings to a file using a template
    template:
      src: dnsmasq.j2
      dest: "/etc/dnsmasq.d/00-header.conf"
  - name: copy grubnetx64.efi.signed
    copy:
      src:
      dest: /srv/tftp/
      mode: '0755'
  - name: copy shimx64.efi.signed
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: '0755'
