- name: setting up the server
  hosts: localhost
  become: true
  roles:
  - server
  vars_prompt:
    - name: "interface"
      prompt: "Enter the correct interface"
      private: no
    - name: "dhcp_start"
      prompt: "Set the dhcp starting range"
      private: no
    - name: "dhcp_end"
      prompt: "Set the dhcp ending range"
      private: no
    - name: "server_ip"
      prompt: "Set the server ip"
      private: no
    - name: "tftp_root"
      prompt: "Set the tftp root directory "
      private: no
      default: "/srv/tftp"
    - name: "MAC"
      prompt: "Enter the device MAC address"
      private: no
    - name: "hostname"
      prompt: "Enter the hostname"
      private: no
    - name: "IP"
      prompt: "Enter the host IP"
      private: no
- name: setting the chroots
  hosts: chroots
  become: yes
  roles:
    - role: server
      tasks_from: chroot.yml
